/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Billboard")]
    [LuaRegisterType(0xd9357e1bb81643a4, typeof(LuaBehaviour))]
    public class Billboard : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "192e5c5042dfc124a8920d58ab177532";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Vector3 _originalScale = new Vector3(1f, 1f, 1f);

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _originalScale),
            };
        }
    }
}

#endif
