/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/CameraCutsceneSettings")]
    [LuaRegisterType(0x2db92f573de7ba83, typeof(LuaScriptableObject))]
    public class CameraCutsceneSettings : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "51c49f8bf92d2604c9e3fa1c12320a1c";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double _pitch = 28;
        [SerializeField] public System.Double _zoom = 20;
        [SerializeField] public System.Double _duration = 0.5;
        [SerializeField] public UnityEngine.Vector3 _targetOffset = new Vector3(0f, 1f, 0f);

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _pitch),
                CreateSerializedProperty(_script.GetPropertyAt(1), _zoom),
                CreateSerializedProperty(_script.GetPropertyAt(2), _duration),
                CreateSerializedProperty(_script.GetPropertyAt(3), _targetOffset),
            };
        }
    }
}

#endif
