/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CheatCommandModule")]
    [LuaRegisterType(0xc892fed52a32f17d, typeof(LuaBehaviour))]
    public class CheatCommandModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1cf27f0c142b2b848b436c0c6fd95879";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean _testMode = false;
        [SerializeField] public System.Collections.Generic.List<System.String> _validPlayers = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _testMode),
                CreateSerializedProperty(_script.GetPropertyAt(1), _validPlayers),
            };
        }
    }
}

#endif
