/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/ClothingCollectionRewardTemplate")]
    [LuaRegisterType(0xfb248bee43c36938, typeof(LuaScriptableObject))]
    public class ClothingCollectionRewardTemplate : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "d7af9898d0cf28149a4d5ee966f20672";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String _id = "";
        [SerializeField] public Highrise.ClothingCollection _collection = default;
        [LuaScriptPropertyAttribute("876ef6e92558ac34d84b32223b9e4acc")]
        [SerializeField] public UnityEngine.Object _displayData = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _id),
                CreateSerializedProperty(_script.GetPropertyAt(1), _collection),
                CreateSerializedProperty(_script.GetPropertyAt(2), _displayData),
            };
        }
    }
}

#endif
