/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/ClothingTemplate")]
    [LuaRegisterType(0x456dc881e79c5dd3, typeof(LuaScriptableObject))]
    public class ClothingTemplate : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "c7dcd8bd689da2645a5c88de673493bd";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String _id = "";
        [SerializeField] public System.String _itemId = "";
        [SerializeField] public System.Double _palette = 0;
        [LuaScriptPropertyAttribute("876ef6e92558ac34d84b32223b9e4acc")]
        [SerializeField] public UnityEngine.Object _displayData = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _id),
                CreateSerializedProperty(_script.GetPropertyAt(1), _itemId),
                CreateSerializedProperty(_script.GetPropertyAt(2), _palette),
                CreateSerializedProperty(_script.GetPropertyAt(3), _displayData),
            };
        }
    }
}

#endif
