/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/ContestTemplate")]
    [LuaRegisterType(0x943530c32474c79d, typeof(LuaScriptableObject))]
    public class ContestTemplate : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "512d9d004b930694888e17854e392cfe";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String _id = "";
        [SerializeField] public System.Collections.Generic.List<System.String> _possibleStyles = default;
        [LuaScriptPropertyAttribute("876ef6e92558ac34d84b32223b9e4acc")]
        [SerializeField] public UnityEngine.Object _displayData = default;
        [SerializeField] public System.Double _duration = 300;
        [SerializeField] public System.Double _ticketCost = 5;
        [SerializeField] public System.Double _topPlayerCount = 10;
        [LuaScriptPropertyAttribute("af271b2a3c7aa6e488d69296c3628b68")]
        [SerializeField] public UnityEngine.Object _participationReward = default;
        [LuaScriptPropertyAttribute("af271b2a3c7aa6e488d69296c3628b68")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _topRewardsList = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _id),
                CreateSerializedProperty(_script.GetPropertyAt(1), _possibleStyles),
                CreateSerializedProperty(_script.GetPropertyAt(2), _displayData),
                CreateSerializedProperty(_script.GetPropertyAt(3), _duration),
                CreateSerializedProperty(_script.GetPropertyAt(4), _ticketCost),
                CreateSerializedProperty(_script.GetPropertyAt(5), _topPlayerCount),
                CreateSerializedProperty(_script.GetPropertyAt(6), _participationReward),
                CreateSerializedProperty(_script.GetPropertyAt(7), _topRewardsList),
            };
        }
    }
}

#endif
