/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ContestManager")]
    [LuaRegisterType(0xacdfa261d6b1b436, typeof(LuaBehaviour))]
    public class ContestManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "495534a8fe6cbb045bce2f8fc0e581cd";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean _cheatsEnabled = true;
        [LuaScriptPropertyAttribute("00c30c064f0d21d40ba941ba9adc07eb")]
        [SerializeField] public UnityEngine.Object _startDateTemplate = default;
        [LuaScriptPropertyAttribute("512d9d004b930694888e17854e392cfe")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _contestTemplates = default;
        [SerializeField] public System.Double _voteOutfitsSentPerRequest = 5;
        [SerializeField] public System.Double _maxVotesPerContest = 10;
        [SerializeField] public System.Double _minOutfitsForVoting = 20;
        [SerializeField] public System.Double _votesPerTicket = 5;
        [SerializeField] public System.Double _previousContestsToStore = 7;
        [SerializeField] public System.Double _saveInterval = 3600;
        [SerializeField] public System.Double _totalStarsPossible = 5;
        [SerializeField] public System.Collections.Generic.List<Highrise.CharacterOutfit> _testCharacterOutfits = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _cheatsEnabled),
                CreateSerializedProperty(_script.GetPropertyAt(1), _startDateTemplate),
                CreateSerializedProperty(_script.GetPropertyAt(2), _contestTemplates),
                CreateSerializedProperty(_script.GetPropertyAt(3), _voteOutfitsSentPerRequest),
                CreateSerializedProperty(_script.GetPropertyAt(4), _maxVotesPerContest),
                CreateSerializedProperty(_script.GetPropertyAt(5), _minOutfitsForVoting),
                CreateSerializedProperty(_script.GetPropertyAt(6), _votesPerTicket),
                CreateSerializedProperty(_script.GetPropertyAt(7), _previousContestsToStore),
                CreateSerializedProperty(_script.GetPropertyAt(8), _saveInterval),
                CreateSerializedProperty(_script.GetPropertyAt(9), _totalStarsPossible),
                CreateSerializedProperty(_script.GetPropertyAt(10), _testCharacterOutfits),
            };
        }
    }
}

#endif
