/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/DateTemplate")]
    [LuaRegisterType(0xfbd54763a943a8bf, typeof(LuaScriptableObject))]
    public class DateTemplate : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "00c30c064f0d21d40ba941ba9adc07eb";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double _startYear = 2020;
        [SerializeField] public System.Double _startMonth = 1;
        [SerializeField] public System.Double _startDay = 1;
        [SerializeField] public System.Double _startHour = 0;
        [SerializeField] public System.Double _startMinute = 0;
        [SerializeField] public System.Double _startSecond = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _startYear),
                CreateSerializedProperty(_script.GetPropertyAt(1), _startMonth),
                CreateSerializedProperty(_script.GetPropertyAt(2), _startDay),
                CreateSerializedProperty(_script.GetPropertyAt(3), _startHour),
                CreateSerializedProperty(_script.GetPropertyAt(4), _startMinute),
                CreateSerializedProperty(_script.GetPropertyAt(5), _startSecond),
            };
        }
    }
}

#endif
