/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DestroyAfterTime")]
    [LuaRegisterType(0x16c45ed1b339ea00, typeof(LuaBehaviour))]
    public class DestroyAfterTime : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6f35391c08182624f92699929aa66146";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double _duration = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _duration),
            };
        }
    }
}

#endif
