/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/DialogTemplate")]
    [LuaRegisterType(0xfe757db124d51f9f, typeof(LuaScriptableObject))]
    public class DialogTemplate : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "a13bdcc9f23e17640b4716b13372c700";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<System.String> _dialogStrings = default;
        [SerializeField] public System.Collections.Generic.List<System.String> _emotes = default;
        [SerializeField] public System.Collections.Generic.List<System.Boolean> _playerSpeakingList = default;
        [SerializeField] public Highrise.AudioShader _speechAudio = default;
        [LuaScriptPropertyAttribute("876ef6e92558ac34d84b32223b9e4acc")]
        [SerializeField] public UnityEngine.Object _displayData = default;
        [SerializeField] public System.Boolean _randomizeStrings = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _dialogStrings),
                CreateSerializedProperty(_script.GetPropertyAt(1), _emotes),
                CreateSerializedProperty(_script.GetPropertyAt(2), _playerSpeakingList),
                CreateSerializedProperty(_script.GetPropertyAt(3), _speechAudio),
                CreateSerializedProperty(_script.GetPropertyAt(4), _displayData),
                CreateSerializedProperty(_script.GetPropertyAt(5), _randomizeStrings),
            };
        }
    }
}

#endif
