/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/DisplayDataTemplate")]
    [LuaRegisterType(0x1b9f412c8628c13b, typeof(LuaScriptableObject))]
    public class DisplayDataTemplate : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "876ef6e92558ac34d84b32223b9e4acc";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String _name = "";
        [SerializeField] public System.String _description = "";
        [SerializeField] public UnityEngine.Sprite _imageSprite = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _name),
                CreateSerializedProperty(_script.GetPropertyAt(1), _description),
                CreateSerializedProperty(_script.GetPropertyAt(2), _imageSprite),
            };
        }
    }
}

#endif
