/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/DressUpNode")]
    [LuaRegisterType(0x67a3ae6a49da65e5, typeof(LuaScriptableObject))]
    public class DressUpNode : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "e7df653cf9c6ff042ac1a79a2954b56d";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.ClothingCollection _clothingCollection = default;
        [LuaScriptPropertyAttribute("876ef6e92558ac34d84b32223b9e4acc")]
        [SerializeField] public UnityEngine.Object _displayData = default;
        [SerializeField] public System.Collections.Generic.List<System.String> _removedClothing = default;
        [SerializeField] public System.Collections.Generic.List<System.String> _extraClothing = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _clothingCollection),
                CreateSerializedProperty(_script.GetPropertyAt(1), _displayData),
                CreateSerializedProperty(_script.GetPropertyAt(2), _removedClothing),
                CreateSerializedProperty(_script.GetPropertyAt(3), _extraClothing),
            };
        }
    }
}

#endif
