/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/DressUpTask")]
    [LuaRegisterType(0x3a97ce16f6c66474, typeof(LuaScriptableObject))]
    public class DressUpTask : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "0a711aa27721882429f1cfea4a46b58d";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String _id = "";
        [SerializeField] public System.Boolean _closetTask = false;
        [Header("Closet Settings")]
        [SerializeField] public Highrise.ClothingCollection _closetClothingCollection = default;
        [SerializeField] public System.Collections.Generic.List<System.String> _typeTargets = default;
        [Header("Choice Settings")]
        [LuaScriptPropertyAttribute("e7df653cf9c6ff042ac1a79a2954b56d")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _characterOutfits = default;
        [SerializeField] public System.Collections.Generic.List<System.Double> _bestChoices = default;
        [Header("Shared Settings")]
        [LuaScriptPropertyAttribute("a13bdcc9f23e17640b4716b13372c700")]
        [SerializeField] public UnityEngine.Object _startDialogTemplate = default;
        [LuaScriptPropertyAttribute("a13bdcc9f23e17640b4716b13372c700")]
        [SerializeField] public UnityEngine.Object _endSuccessDialogTemplate = default;
        [LuaScriptPropertyAttribute("a13bdcc9f23e17640b4716b13372c700")]
        [SerializeField] public UnityEngine.Object _endFailDialogTemplate = default;
        [LuaScriptPropertyAttribute("af271b2a3c7aa6e488d69296c3628b68")]
        [SerializeField] public UnityEngine.Object _lootContainerTemplate = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _id),
                CreateSerializedProperty(_script.GetPropertyAt(1), _closetTask),
                CreateSerializedProperty(_script.GetPropertyAt(2), _closetClothingCollection),
                CreateSerializedProperty(_script.GetPropertyAt(3), _typeTargets),
                CreateSerializedProperty(_script.GetPropertyAt(4), _characterOutfits),
                CreateSerializedProperty(_script.GetPropertyAt(5), _bestChoices),
                CreateSerializedProperty(_script.GetPropertyAt(6), _startDialogTemplate),
                CreateSerializedProperty(_script.GetPropertyAt(7), _endSuccessDialogTemplate),
                CreateSerializedProperty(_script.GetPropertyAt(8), _endFailDialogTemplate),
                CreateSerializedProperty(_script.GetPropertyAt(9), _lootContainerTemplate),
            };
        }
    }
}

#endif
