/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FloatTween")]
    [LuaRegisterType(0xa075666897ca59fc, typeof(LuaBehaviour))]
    public class FloatTween : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "ff024d489b8801e4da0a193ed7b7f40e";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Vector3 _offset = new Vector3(0f, 0f, 0f);
        [SerializeField] public System.Double _duration = 0.2;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _offset),
                CreateSerializedProperty(_script.GetPropertyAt(1), _duration),
            };
        }
    }
}

#endif
