/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GameManager")]
    [LuaRegisterType(0x64f367123469100e, typeof(LuaBehaviour))]
    public class GameManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "5608a2584d89809428c7e07bfd28c894";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("e4857184bfb273d40b3b6f28fe01513a")]
        [SerializeField] public UnityEngine.Object _gameSettings = default;
        [LuaScriptPropertyAttribute("61ef0aee74211264c905a5e9b57a7847")]
        [SerializeField] public UnityEngine.Object _chatDispatcher = default;
        [LuaScriptPropertyAttribute("fb89e40385eb2314a954e955fa479b37")]
        [SerializeField] public UnityEngine.Object _mainUI = default;
        [LuaScriptPropertyAttribute("495534a8fe6cbb045bce2f8fc0e581cd")]
        [SerializeField] public UnityEngine.Object _contestManager = default;
        [SerializeField] public Highrise.Client.Characters.Character _contestNPC = default;
        [LuaScriptPropertyAttribute("fba500c3acc6b2c4baa0dd9a0c8f73e5")]
        [SerializeField] public UnityEngine.Object _unlockContestsAfterQuest = default;
        [LuaScriptPropertyAttribute("fba500c3acc6b2c4baa0dd9a0c8f73e5")]
        [SerializeField] public UnityEngine.Object _contestQuest = default;
        [LuaScriptPropertyAttribute("fba500c3acc6b2c4baa0dd9a0c8f73e5")]
        [SerializeField] public UnityEngine.Object _finalQuest = default;
        [SerializeField] public Highrise.AudioShader _mainMusic = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _additionalIncludedFiles = default;
        [Header("Camera Settings")]
        [LuaScriptPropertyAttribute("51c49f8bf92d2604c9e3fa1c12320a1c")]
        [SerializeField] public UnityEngine.Object _dressUpCameraSettings = default;
        [LuaScriptPropertyAttribute("51c49f8bf92d2604c9e3fa1c12320a1c")]
        [SerializeField] public UnityEngine.Object _defaultCameraSettings = default;
        [SerializeField] public UnityEngine.Camera _mainCamera = default;
        [SerializeField] public System.Boolean _closetDevMode = false;
        [SerializeField] public System.Boolean _useOldCloset = false;
        [SerializeField] public System.Boolean _testSendQuestsOutfitsToContest = false;
        [SerializeField] public System.Boolean _testAddDebugPlayersForContest = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _gameSettings),
                CreateSerializedProperty(_script.GetPropertyAt(1), _chatDispatcher),
                CreateSerializedProperty(_script.GetPropertyAt(2), _mainUI),
                CreateSerializedProperty(_script.GetPropertyAt(3), _contestManager),
                CreateSerializedProperty(_script.GetPropertyAt(4), _contestNPC),
                CreateSerializedProperty(_script.GetPropertyAt(5), _unlockContestsAfterQuest),
                CreateSerializedProperty(_script.GetPropertyAt(6), _contestQuest),
                CreateSerializedProperty(_script.GetPropertyAt(7), _finalQuest),
                CreateSerializedProperty(_script.GetPropertyAt(8), _mainMusic),
                CreateSerializedProperty(_script.GetPropertyAt(9), _additionalIncludedFiles),
                CreateSerializedProperty(_script.GetPropertyAt(10), _dressUpCameraSettings),
                CreateSerializedProperty(_script.GetPropertyAt(11), _defaultCameraSettings),
                CreateSerializedProperty(_script.GetPropertyAt(12), _mainCamera),
                CreateSerializedProperty(_script.GetPropertyAt(13), _closetDevMode),
                CreateSerializedProperty(_script.GetPropertyAt(14), _useOldCloset),
                CreateSerializedProperty(_script.GetPropertyAt(15), _testSendQuestsOutfitsToContest),
                CreateSerializedProperty(_script.GetPropertyAt(16), _testAddDebugPlayersForContest),
            };
        }
    }
}

#endif
