/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/GameSettings")]
    [LuaRegisterType(0x41446629c6b10f7a, typeof(LuaScriptableObject))]
    public class GameSettings : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "e4857184bfb273d40b3b6f28fe01513a";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("876ef6e92558ac34d84b32223b9e4acc")]
        [SerializeField] public UnityEngine.Object _playerDisplayData = default;
        [LuaScriptPropertyAttribute("a13bdcc9f23e17640b4716b13372c700")]
        [SerializeField] public UnityEngine.Object _questAlreadyCompleteDialog = default;
        [LuaScriptPropertyAttribute("a13bdcc9f23e17640b4716b13372c700")]
        [SerializeField] public UnityEngine.Object _resetQuestsDialog = default;
        [LuaScriptPropertyAttribute("8b26def9bece48447a02008d370991d2")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _currencyList = default;
        [LuaScriptPropertyAttribute("c7dcd8bd689da2645a5c88de673493bd")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _clothingList = default;
        [LuaScriptPropertyAttribute("d7af9898d0cf28149a4d5ee966f20672")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _clothingCollectionRewardList = default;
        [LuaScriptPropertyAttribute("012b2e69a916e624f82cc45810d0b5cd")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _itemStoreList = default;
        [LuaScriptPropertyAttribute("97cb8c970dd409247818327ea766fc96")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _questLines = default;
        [LuaScriptPropertyAttribute("0a711aa27721882429f1cfea4a46b58d")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _dressUpTasks = default;
        [LuaScriptPropertyAttribute("a13bdcc9f23e17640b4716b13372c700")]
        [SerializeField] public UnityEngine.Object _questNotUnlockedDialog = default;
        [SerializeField] public System.Double _percentChoicesCorrectToSucceed = 0.9;
        [SerializeField] public Highrise.AudioShader _dressUpCompleteSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _playerDisplayData),
                CreateSerializedProperty(_script.GetPropertyAt(1), _questAlreadyCompleteDialog),
                CreateSerializedProperty(_script.GetPropertyAt(2), _resetQuestsDialog),
                CreateSerializedProperty(_script.GetPropertyAt(3), _currencyList),
                CreateSerializedProperty(_script.GetPropertyAt(4), _clothingList),
                CreateSerializedProperty(_script.GetPropertyAt(5), _clothingCollectionRewardList),
                CreateSerializedProperty(_script.GetPropertyAt(6), _itemStoreList),
                CreateSerializedProperty(_script.GetPropertyAt(7), _questLines),
                CreateSerializedProperty(_script.GetPropertyAt(8), _dressUpTasks),
                CreateSerializedProperty(_script.GetPropertyAt(9), _questNotUnlockedDialog),
                CreateSerializedProperty(_script.GetPropertyAt(10), _percentChoicesCorrectToSucceed),
                CreateSerializedProperty(_script.GetPropertyAt(11), _dressUpCompleteSound),
            };
        }
    }
}

#endif
