/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/LootContainerTemplate")]
    [LuaRegisterType(0x2a55942ad3b32e44, typeof(LuaScriptableObject))]
    public class LootContainerTemplate : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "af271b2a3c7aa6e488d69296c3628b68";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("f6f2a1dbb87577d4bbf7363df413c0b1")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _guaranteedLootList = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Vector3> _guaranteedLootRanges = default;
        [Header("Additional Loot Settings")]
        [SerializeField] public UnityEngine.Vector3 _additionalLootCountRange = new Vector3(0f, 0f, 0f);
        [LuaScriptPropertyAttribute("f6f2a1dbb87577d4bbf7363df413c0b1")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _additionalLootList = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Vector3> _additionalLootRanges = default;
        [SerializeField] public System.Collections.Generic.List<System.Double> _additionalLootWeights = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _guaranteedLootList),
                CreateSerializedProperty(_script.GetPropertyAt(1), _guaranteedLootRanges),
                CreateSerializedProperty(_script.GetPropertyAt(2), _additionalLootCountRange),
                CreateSerializedProperty(_script.GetPropertyAt(3), _additionalLootList),
                CreateSerializedProperty(_script.GetPropertyAt(4), _additionalLootRanges),
                CreateSerializedProperty(_script.GetPropertyAt(5), _additionalLootWeights),
            };
        }
    }
}

#endif
