/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/NPCDressUpTaskController")]
    [LuaRegisterType(0x8f261e53c5e13c7f, typeof(LuaBehaviour))]
    public class NPCDressUpTaskController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "aeecef89e059d9c44bba0a730ae1b98d";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("0a711aa27721882429f1cfea4a46b58d")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _dressUpTasks = default;
        [LuaScriptPropertyAttribute("fba500c3acc6b2c4baa0dd9a0c8f73e5")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _questTemplates = default;
        [SerializeField] public System.Collections.Generic.List<Highrise.CharacterOutfit> _outfits = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Transform> _nodeAnchors = default;
        [SerializeField] public UnityEngine.GameObject _questObject = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> _hideObjectsInCutscene = default;
        [SerializeField] public System.Boolean _resetDataNPC = false;
        [SerializeField] public System.Boolean _autoCompleteForTesting = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _dressUpTasks),
                CreateSerializedProperty(_script.GetPropertyAt(1), _questTemplates),
                CreateSerializedProperty(_script.GetPropertyAt(2), _outfits),
                CreateSerializedProperty(_script.GetPropertyAt(3), _nodeAnchors),
                CreateSerializedProperty(_script.GetPropertyAt(4), _questObject),
                CreateSerializedProperty(_script.GetPropertyAt(5), _hideObjectsInCutscene),
                CreateSerializedProperty(_script.GetPropertyAt(6), _resetDataNPC),
                CreateSerializedProperty(_script.GetPropertyAt(7), _autoCompleteForTesting),
            };
        }
    }
}

#endif
