/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/OpenContestUITrigger")]
    [LuaRegisterType(0xa478700c7f67aff7, typeof(LuaBehaviour))]
    public class OpenContestUITrigger : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f2de6ccd24e564649b13b503a14a5218";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("a13bdcc9f23e17640b4716b13372c700")]
        [SerializeField] public UnityEngine.Object _notUnlockedDialog = default;
        [SerializeField] public Highrise.Client.Characters.Character _npcCharacter = default;
        [SerializeField] public UnityEngine.GameObject _notifyObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _notUnlockedDialog),
                CreateSerializedProperty(_script.GetPropertyAt(1), _npcCharacter),
                CreateSerializedProperty(_script.GetPropertyAt(2), _notifyObject),
            };
        }
    }
}

#endif
