/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/OpenStoreTrigger")]
    [LuaRegisterType(0x68a1c406e8634382, typeof(LuaBehaviour))]
    public class OpenStoreTrigger : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "25b69a5094d07bd41bebcc12be0521e2";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.Client.Characters.Character _npcCharacter = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _npcCharacter),
            };
        }
    }
}

#endif
