/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/QuestTemplate")]
    [LuaRegisterType(0x921df0ba02b8e203, typeof(LuaScriptableObject))]
    public class QuestTemplate : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "fba500c3acc6b2c4baa0dd9a0c8f73e5";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String _id = "";
        [SerializeField] public System.String _questText = "";
        [SerializeField] public System.String _goalDescription = "";
        [LuaScriptPropertyAttribute("876ef6e92558ac34d84b32223b9e4acc")]
        [SerializeField] public UnityEngine.Object _displayData = default;
        [SerializeField] public System.Double _targetAmount = 1;
        [LuaScriptPropertyAttribute("4d4dd9c7c4b0b3642bc19dbde3f6a64a")]
        [SerializeField] public UnityEngine.Object _requirement = default;
        [LuaScriptPropertyAttribute("af271b2a3c7aa6e488d69296c3628b68")]
        [SerializeField] public UnityEngine.Object _lootContainerTemplate = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _id),
                CreateSerializedProperty(_script.GetPropertyAt(1), _questText),
                CreateSerializedProperty(_script.GetPropertyAt(2), _goalDescription),
                CreateSerializedProperty(_script.GetPropertyAt(3), _displayData),
                CreateSerializedProperty(_script.GetPropertyAt(4), _targetAmount),
                CreateSerializedProperty(_script.GetPropertyAt(5), _requirement),
                CreateSerializedProperty(_script.GetPropertyAt(6), _lootContainerTemplate),
            };
        }
    }
}

#endif
