/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/QuestManager")]
    [LuaRegisterType(0x2a1d82c79bbe8ab4, typeof(LuaBehaviour))]
    public class QuestManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "bc4b0d1ff1cce1f479d1cdd780a33303";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("aeecef89e059d9c44bba0a730ae1b98d")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _dressUpTasks = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _dressUpTasks),
            };
        }
    }
}

#endif
