/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/QuestLineTemplate")]
    [LuaRegisterType(0x7cedd8d36a70a4ed, typeof(LuaScriptableObject))]
    public class QuestLineTemplate : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "97cb8c970dd409247818327ea766fc96";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String _id = "";
        [LuaScriptPropertyAttribute("fba500c3acc6b2c4baa0dd9a0c8f73e5")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _quests = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _id),
                CreateSerializedProperty(_script.GetPropertyAt(1), _quests),
            };
        }
    }
}

#endif
