/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIContestResults")]
    [LuaRegisterType(0x745357d8d545dc81, typeof(LuaBehaviour))]
    public class UIContestResults : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b50577192a120614e8b9f5d7978ea383";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.Client.Characters.Character _dressUpNPC = default;
        [SerializeField] public UnityEngine.Transform _cameraTarget = default;
        [SerializeField] public UnityEngine.Sprite _starSprite = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), _dressUpNPC),
                CreateSerializedProperty(_script.GetPropertyAt(3), _cameraTarget),
                CreateSerializedProperty(_script.GetPropertyAt(4), _starSprite),
            };
        }
    }
}

#endif
