/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIDialog")]
    [LuaRegisterType(0xf957ba8b86edf217, typeof(LuaBehaviour))]
    public class UIDialog : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6a32e0e05d0f66143af1b615f5eb58c9";
        public override string ScriptGUID => s_scriptGUID;

        [Header("Dialog Settings")]
        [SerializeField] public System.Double _animateTextSpeed = 0.1;
        [SerializeField] public System.Double _nameplateRotateAmount = 10;
        [SerializeField] public System.Double _nameplateRotateDuration = 2;
        [SerializeField] public System.Double _nameplateRotateDelay = 0.75;
        [SerializeField] public System.Double _speechAudioDelay = 0.4;
        [SerializeField] public System.Double _charactersFromEndToStopAudio = 10;
        [Header("Arrow Animation Settings")]
        [SerializeField] public System.Double _arrowMoveDuration = 1;
        [SerializeField] public System.Double _arrowMoveDistance = 10;
        [SerializeField] public System.Double _arrowBotStart = 10;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
                CreateSerializedProperty(_script.GetPropertyAt(6), _animateTextSpeed),
                CreateSerializedProperty(_script.GetPropertyAt(7), _nameplateRotateAmount),
                CreateSerializedProperty(_script.GetPropertyAt(8), _nameplateRotateDuration),
                CreateSerializedProperty(_script.GetPropertyAt(9), _nameplateRotateDelay),
                CreateSerializedProperty(_script.GetPropertyAt(10), _speechAudioDelay),
                CreateSerializedProperty(_script.GetPropertyAt(11), _charactersFromEndToStopAudio),
                CreateSerializedProperty(_script.GetPropertyAt(12), _arrowMoveDuration),
                CreateSerializedProperty(_script.GetPropertyAt(13), _arrowMoveDistance),
                CreateSerializedProperty(_script.GetPropertyAt(14), _arrowBotStart),
            };
        }
    }
}

#endif
