/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIDressUpNode")]
    [LuaRegisterType(0x8259e9fca84a2e6b, typeof(LuaBehaviour))]
    public class UIDressUpNode : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8c8473b307055f7488d65fa6cbf3f487";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double _nodeAnimDuration = 0.5;
        [SerializeField] public Highrise.AudioShader _scaelUpSound = default;
        [SerializeField] public System.Double _pulseTime = 1;
        [SerializeField] public System.Double _pulseSize = 1.1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), _nodeAnimDuration),
                CreateSerializedProperty(_script.GetPropertyAt(4), _scaelUpSound),
                CreateSerializedProperty(_script.GetPropertyAt(5), _pulseTime),
                CreateSerializedProperty(_script.GetPropertyAt(6), _pulseSize),
            };
        }
    }
}

#endif
