/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIItemStore")]
    [LuaRegisterType(0xd3705e7dd548f22d, typeof(LuaBehaviour))]
    public class UIItemStore : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "38a442c58818fc44985126c78819655a";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("8b26def9bece48447a02008d370991d2")]
        [SerializeField] public UnityEngine.Object _currencyBalanceTemplate = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _currencyBalanceTemplate),
            };
        }
    }
}

#endif
