/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIPopupAnimateHelper")]
    [LuaRegisterType(0x4db52b16df9d5d5a, typeof(LuaBehaviour))]
    public class UIPopupAnimateHelper : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "0febfdce13aa797429dbc17eb37e3229";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double _openCloseDuration = 0.5;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _openCloseDuration),
            };
        }
    }
}

#endif
