/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIQuestHud")]
    [LuaRegisterType(0x51bdd53ec3f4c580, typeof(LuaBehaviour))]
    public class UIQuestHud : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "9a0a0db822ad38e4ba1be14cfacce956";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double _delayToShowQuests = 1;
        [SerializeField] public Highrise.AudioShader _questCompleteSound = default;
        [SerializeField] public Highrise.AudioShader _newQuestSound = default;
        [SerializeField] public System.Double _delayAfterSlideOutToShowNew = 0.5;
        [SerializeField] public System.Double _questCompleteDelay = 2;
        [SerializeField] public System.Double _slideAnimDuration = 0.25;
        [SerializeField] public System.Double _extraSlidePadding = 10;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), _delayToShowQuests),
                CreateSerializedProperty(_script.GetPropertyAt(4), _questCompleteSound),
                CreateSerializedProperty(_script.GetPropertyAt(5), _newQuestSound),
                CreateSerializedProperty(_script.GetPropertyAt(6), _delayAfterSlideOutToShowNew),
                CreateSerializedProperty(_script.GetPropertyAt(7), _questCompleteDelay),
                CreateSerializedProperty(_script.GetPropertyAt(8), _slideAnimDuration),
                CreateSerializedProperty(_script.GetPropertyAt(9), _extraSlidePadding),
            };
        }
    }
}

#endif
