/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIReward")]
    [LuaRegisterType(0xd7d85c908124ac, typeof(LuaBehaviour))]
    public class UIReward : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e1c8054dc9b953b44bbb28f6dc948d16";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader _rewardsOpenedSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), _rewardsOpenedSound),
            };
        }
    }
}

#endif
